#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.10

pipelines:
    custom:
        - step:
            name: Test
            caches:
              - pip
            script:
              - pip install -r requirements.txt
              - pytest -v --cov-report html --cov="." --cov-append
    branches:
      master:
        - step:
            name: Installing and running tox.
            script:
              - pip install -U tox
              - pip --version
              - tox --version
              # Actually run tox.
              - tox



      # - step:
      #     name: Lint code
      #     script:
      #       # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
      #       - pip install flake8
      #       - flake8 . --extend-exclude=dist,build --show-source --statistics
