#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.10

pipelines:
  default:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            #- pytest -v tests/* --junitxml=test-reports/report.xml
            - pytest -v --cov-report html --cov="." --cov-append
      # - step:
      #     name: Lint code
      #     script:
      #       # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
      #       - pip install flake8
      #       - flake8 . --extend-exclude=dist,build --show-source --statistics
