[project]
name = "sv_regression"
version = "0.0.1"
authors = [
  { name="Yannick Stoll, Elidjah Maugalem", emails="yannick@pixelforest.io, elidjah@pixelforest.io "  },
]
description = "A library for shapley value regression"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: GNU General Public License v3 (GPLv3)", 
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://bitbucket.org/pixelforest/sv_regression/src/master/"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

